### ISSUE TITLE
RuntimeError: CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by TheCrappyActionFigureMaster** [HiFi-Human/DualGS#8]
I kept running into this error when training skin for frame 1 
( running the guitar dataset with undistorted images.)

Output folder: /media/dual_output/guitar_test/ [06/11 16:59:10]
Reading camera 81/81 [06/11 16:59:10]
Loading Training Cameras [06/11 16:59:10]
Loading Test Cameras [06/11 16:59:13]
[16:59:13] loading motion from control point                                                              __init__.py:84 [06/11 16:59:13]
[16:59:14] Loading ply file :  /media/dual_output/guitar_test/ckt/point_cloud_0.ply gaussian_model.py:290 [06/11 16:59:14]
number of gaussians: 215771 [06/11 16:59:14]
Training progress:   0%|                                                                     | 0/15000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/media/DualGS/train.py", line 383, in <module>
    training_skin(lp.extract(args), op.extract(args), pp.extract(args), lossp2, args.test_iterations, args.debug_from, is_start_frame, frame_idx, args=args)
  File "/media/DualGS/train.py", line 235, in training_skin
    loss.backward()
  File "/home/anaconda3/envs/dualgs/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/anaconda3/envs/dualgs/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Training progress:   0%|                                                                     | 0/15000 [00:01<?, ?it/s]

Any possible cause or solution?
Any help will be very much appreciated!! thanks!!

**Comment by moqiyinlun** [comment]
This might be because you are using a different rasterization method. You can first try the original Gaussian rasterizer to see if it produces the desired results.

**Comment by Anderson-Wu** [comment]
I also encountered this problem, and I fixed it by increasing the value of l in skin2JointInterpolation and graph_init. Maybe this change will help you. I think the issue was caused by some NaN values.

**Comment by NineTwoMay1st** [comment]
> I also encountered this problem, and I fixed it by increasing the value of l in skin2JointInterpolation and graph_init. Maybe this change will help you. I think the issue was caused by some NaN values.
Could you please tell me where I can modify this? Thank   @Anderson-Wu
